---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - ansible-lint --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  script:
    - pip install git+https://github.com/ansible/ansible-lint.git
    - ansible-lint . -c .ansible-lint
  tags:
    - aws

.Docker mysql:
  stage: deployment test
  script:
    - molecule test -s default
  tags:
    - aws

.AWS mysql 5.7:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-5.7
  tags:
    - aws


AWS mysql 5.6:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-5.6
  tags:
    - aws

.AWS mysql 5.5:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-5.5
  tags:
    - aws

.AWS mysql mariadb:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-mariadb
  tags:
    - aws

.AWS mysql-8.0:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-8.0
  tags:
    - aws

.EPC mysql-5.5:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated-5.5
  tags:
    - delegated

.EPC mysql-5.6:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated-5.6
  tags:
    - delegated

.EPC mysql-5.7:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated-5.7
  tags:
    - delegated

.EPC mariadb:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated-mariadb
  tags:
    - delegated
