---
- name: Ensure MySQL databases are present
  mysql_db:
    name: '{{ item.name }}'
    collation: '{{ item.collation | default("utf8_general_ci") }}'
    encoding: '{{ item.encoding | default("utf8") }}'
    state: '{{ item.state | default("present") }}'
    target: '{{ item.target | default(None) }}'
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
  loop: '{{ mysql_databases }}'
  become: True

- name: Ensure MySQL users are present
  mysql_user:
    name: '{{ item.name }}'
    host: '{{ item.host | default("localhost") }}'
    password: '{{ item.password }}'
    priv: '{{ item.priv | default("*.*:USAGE") }}'
    state: '{{ item.state | default("present") }}'
    append_privs: '{{ item.append_privs | default("False") }}'
    encrypted: '{{ item.encrypted | default("False") }}'
    login_user: '{{ mysql_root_username }}'
    login_password: '{{ mysql_root_password }}'
    #update_password: on_create
  loop: '{{ mysql_users }}'
  no_log: True
  become: True
