---
- name: Stop and start mysql service
  block:
    - name: Stop mysql
      service:
        name: '{{ mysql_service_name }}'
        state: stopped

    - name: Wait until the lock file is removed
      wait_for:
        path: /var/lock/subsys/mysql
        state: absent

    - name: Start mysql
      service:
        name: '{{ mysql_service_name }}'
        state: started
  become: true

- name: Wait for service to be ready
  wait_for:
    port: '{{ mysql_port }}'
    host: '{{ mysql_bind_address }}'
    connect_timeout: 3
    delay: 3
    timeout: 30
